/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFrame;

/**
 *
 * @author admin
 */
public class PrincipalBibliotecaria extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalBibliotecaria
     */
    public PrincipalBibliotecaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        ItemAssunto = new javax.swing.JMenuItem();
        ItemAutor = new javax.swing.JMenuItem();
        ItemEditora = new javax.swing.JMenuItem();
        ItemLivro = new javax.swing.JMenuItem();
        ItemExemplar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bibliotecaria");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        MenuCadastro.setText("Cadastros");

        ItemAssunto.setText("Assuntos");
        ItemAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAssuntoActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemAssunto);

        ItemAutor.setText("Autores");
        ItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAutorActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemAutor);

        ItemEditora.setText("Editoras");
        ItemEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditoraActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemEditora);

        ItemLivro.setText("Livros");
        ItemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemLivroActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemLivro);

        ItemExemplar.setText("Exemplar");
        ItemExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemExemplarActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemExemplar);

        jMenuItem1.setText("Categoria de Leitor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuCadastro.add(jMenuItem1);

        jMenuBar1.add(MenuCadastro);

        MenuRelatorio.setText("Relatorio");

        jMenuItem2.setText("Relatorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenuItem2);

        jMenuBar1.add(MenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(514, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAssuntoActionPerformed
         
        new Assunto.CadastroAssunto().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAssuntoActionPerformed

    private void ItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAutorActionPerformed
        // TODO add your handling code here:
        new Autor.CadastroAutor().setVisible(true);
    }//GEN-LAST:event_ItemAutorActionPerformed

    private void ItemEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditoraActionPerformed

        new Editora.CadastroEditora().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditoraActionPerformed

    private void ItemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemLivroActionPerformed

        new Livro.CadastroLivro().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemLivroActionPerformed

    private void ItemExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemExemplarActionPerformed

        new Livro.Exemplar.CadastroExemplar().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemExemplarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CategoriaLeitor.CadastroCatLeitor().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Relatorio.Principal1Biliotecaria().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalBibliotecaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalBibliotecaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAssunto;
    private javax.swing.JMenuItem ItemAutor;
    private javax.swing.JMenuItem ItemEditora;
    private javax.swing.JMenuItem ItemExemplar;
    private javax.swing.JMenuItem ItemLivro;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
